### ISSUE TITLE
Elastix implementation streamlined python pipeline

### ISSUE THREAD

**Issue by andrestrocyte** [DeNardoLab/DeepTraCE#2]
Hello!

I am currently trying to use the streamlined version of the pipeline with the test data. TRAILMAP has worked well and generated the tiffs with the segmented axons.

The code is breaking when running the elastix transformation. In the preferences json file I have pointed to the location of the elastix executable. 

When running the code, I get this error (find at the bottom of the message).

I think that my elastix is not generating some files properly, but the location of the binaries is correct. Thus, I am blocked at this step and would appreciate a lot any possible input.

Thanks for developing DeepTrace!

[0.0, 28.0]
[DeepTraCE] Fitting the alignment channel with elastix
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
D:\temp\TEMPdeviandr\ipykernel_20384\97161989.py in ?()
---> 21 # This will open the figure for you to select the angles
     22 get_ipython().run_line_magic('matplotlib', 'qt')
     23 # The line above is needed select the angles interactively
     24 

D:\PIXI_CACHE\envs\gluthi_axonal-tracing-6923454288390063666\envs\default\lib\site-packages\deeptrace\analysis.py in ?(self, angles, flip_x, flip_y, scales, trailmap_models, trailmap_channel, pbar)
    277         transform_path = pjoin(self.analysis_folder,'transformix')
    278         if not os.path.exists(transform_path):
    279             print('[DeepTraCE] Fitting the alignment channel with elastix')
    280             from .elastix_utils import elastix_fit
--> 281             aligned,transformpaths = elastix_fit(to_elastix, pbar = pbar)
    282             os.makedirs(transform_path,exist_ok = True)
    283             for f in transformpaths:
    284                 shutil.copyfile(f, pjoin(transform_path,os.path.basename(f)))

D:\PIXI_CACHE\envs\gluthi_axonal-tracing-6923454288390063666\envs\default\lib\site-packages\deeptrace\elastix_utils.py in ?(stack, elastix_path, registration_template, par0, par1, outpath, pbar)
    207     transformix_parameters_paths = (pjoin(outpath,'TransformParameters.0.txt'),
    208                                     pjoin(outpath,'TransformParameters.1.txt')) # needs to be both for transformix, copy these together
    209     # The output filename will depend on the transforms..
    210     # clip to uint8
--> 211     return np.clip(imread(pjoin(outpath,'result.1.tiff')),0,255).astype('uint8'), transformix_parameters_paths

D:\PIXI_CACHE\envs\gluthi_axonal-tracing-6923454288390063666\envs\default\lib\site-packages\tifffile\tifffile.py in ?(files, aszarr, **kwargs)
    887         ):
    888             files = files[0]
    889 
    890         if isinstance(files, (str, os.PathLike)) or hasattr(files, 'seek'):
--> 891             with TiffFile(files, **kwargs_file) as tif:
    892                 if aszarr:
    893                     return tif.aszarr(**kwargs)
    894                 return tif.asarray(**kwargs)

D:\PIXI_CACHE\envs\gluthi_axonal-tracing-6923454288390063666\envs\default\lib\site-packages\tifffile\tifffile.py in ?(self, arg, mode, name, offset, size, _multifile, _useframes, _parent, **kwargs)
   3127 
   3128         if mode not in (None, 'rb', 'r+b'):
   3129             raise ValueError(f'invalid mode {mode!r}')
   3130 
-> 3131         fh = FileHandle(arg, mode=mode, name=name, offset=offset, size=size)
   3132         self._fh = fh
   3133         self._multifile = bool(_multifile)
   3134         self._files = {fh.name: self}  # cache of TiffFile instances

D:\PIXI_CACHE\envs\gluthi_axonal-tracing-6923454288390063666\envs\default\lib\site-packages\tifffile\tifffile.py in ?(self, file, mode, name, offset, size)
  10443         self._size = size
  10444         self._close = True
  10445         self.is_file = None
  10446         self._lock = NullContext()
> 10447         self.open()

D:\PIXI_CACHE\envs\gluthi_axonal-tracing-6923454288390063666\envs\default\lib\site-packages\tifffile\tifffile.py in ?(self)
  10456         if isinstance(self._file, str):
  10457             # file name
  10458             self._file = os.path.realpath(self._file)
  10459             self._dir, self._name = os.path.split(self._file)
> 10460             self._fh = open(self._file, self._mode)
  10461             self._close = True
  10462             if self._offset is None:
  10463                 self._offset = 0

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\deviandr\\DeepTraCE\\temp\\result.1.tiff'

**Comment by andrestrocyte** [comment]
@jcouto

**Comment by jcouto** [comment]
Hi @andrestrocyte 

apologies for the latency. 

Let me know if this is still an issue. To debug I would ask if the "C:\Users\deviandr\DeepTraCE\temp\" folder exists? 
If it does not exist, does it run if you create it by hand? 

Inside that folder there should be a couple of logs that can help further debugging.

Best, Joao

**Comment by andrestrocyte** [comment]
Hi @jcouto , thanks so much for your help.

Indeed, everything was solved when manually creating the temp folder. I replicated this issue and solution in 2 PCs.

After that. the pipeline works really well and I replicated your results with the test images.

I am now trying to implement in the Python pipeline some code to also be able to generate what the MATLAB pipeline does (dotogram, PCA, multi brains colorised). I will upload this to my branch once I manage. Also displaying the interactive atlas in a coronal orientation. Just using the csv and tiffs that the Python code gave me in MATLAB gave me errors when running. But happy to receive any input regarding this.

Also, from what I understood the pipeline works if the raw data is in the sagittal orientation. I already wrote a Python scripts to rotate the image in the case the LightSheet takes it transverse or coronal. TransformJ as the MATLAB pipeline suggest I think would also be a nice option. Will soon push in my branch.

Thanks for developing this, hope to test it soon with my own data too.

Andres

**Comment by jcouto** [comment]
Hi @andrestrocyte, thanks for finding this, I pushed a fix but haven't tested in another installation. Will test when I have a minute.

Fantastic on the dotogram and other improvements, I'll add you as a collaborator so you can manage merges after testing if you want. 

Best, Joao
